/**
 * CC ERP — Schema Mock Data
 * File: src/mocks/schemaMocks.js
 *
 * Used ONLY in dev mode when window.google.script.run is unavailable.
 * Mirrors the EXACT JSON structure returned by getSchemaSnapshot() in GAS.
 *
 * Keep in sync with Masters_V9.xlsx column definitions.
 * Never import this in production builds.
 *
 * Shape of each field object must match GAS exactly:
 * {
 *   colIndex, key, rawHeader, icon, iconType,
 *   displayLabel, renderType, type, mandatory, editable,
 *   autoGenerated, fk, fkSheet, validation, hint
 * }
 */

// ─── ICON → iconType MAP (mirrors GAS) ───────────────────────────────────────
// "🔑" → PRIMARY_KEY
// "#"  → AUTO_CODE
// "⚠"  → MANDATORY
// "→"  → FK
// "←"  → AUTO_DISPLAY
// "⟷"  → SYNC
// "∑"  → CALCULATED
// ""   → TEXT

// ─── ARTICLE_MASTER (26 cols per BUILD_REF_V7) ────────────────────────────────
const ARTICLE_MASTER = {
  sheetName:   "ARTICLE_MASTER",
  fileLabel:   "FILE-1A",
  tabColor:    "#4a86e8",
  totalColumns: 26,
  dataStartRow: 4,
  fields: [
    { colIndex:1,  key:"Article Code",         rawHeader:"🔑 Article Code",         icon:"🔑", iconType:"PRIMARY_KEY",  displayLabel:"Article Code",         renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"regex:^[0-9]{4,5}[A-Z]{2}$", hint:"Format: 5249HP — no spaces" },
    { colIndex:2,  key:"Article Description",  rawHeader:"⚠ Article Description",   icon:"⚠",  iconType:"MANDATORY",    displayLabel:"Article Description",  renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null,                          hint:"Full name with fabric construction" },
    { colIndex:3,  key:"Short Name",           rawHeader:"Short Name",               icon:"",   iconType:"TEXT",         displayLabel:"Short Name",           renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null,                          hint:"Max 25 chars — for barcode/tag" },
    { colIndex:4,  key:"IMAGE LINK",           rawHeader:"IMAGE LINK",               icon:"",   iconType:"TEXT",         displayLabel:"Product Image",        renderType:"image_url", mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null,                          hint:"Google Drive image link" },
    { colIndex:5,  key:"SKETCH DRIVE LINKS",   rawHeader:"⟷ SKETCH DRIVE LINKS",    icon:"⟷",  iconType:"SYNC",         displayLabel:"Sketch / Design Links",renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null,                          hint:"GAS appends ArticleCode-DyeingPlanNo-Date. Never overwrites." },
    { colIndex:6,  key:"Buyer Style No",       rawHeader:"Buyer Style No",           icon:"",   iconType:"TEXT",         displayLabel:"Buyer Style No",       renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null,                          hint:"Optional — buyer reference" },
    { colIndex:7,  key:"L1 Division",          rawHeader:"← L1 Division",           icon:"←",  iconType:"AUTO_DISPLAY", displayLabel:"L1 Division",          renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null,                  validation:null,                          hint:null },
    { colIndex:8,  key:"L2 Product Category",  rawHeader:"⚠ L2 Product Category",   icon:"⚠",  iconType:"MANDATORY",    displayLabel:"Product Category",     renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"options:Tops-Polo,Tops-Tee,Sweatshirt,Tracksuit,Bottoms", hint:"Tops-Polo / Tops-Tee / Sweatshirt / Tracksuit / Bottoms" },
    { colIndex:9,  key:"Season",               rawHeader:"⟷ Season",                icon:"⟷",  iconType:"SYNC",         displayLabel:"Season",               renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null,                          hint:"SS25 / AW25 / SS26 / AW26 / Year Round" },
    { colIndex:10, key:"Gender",               rawHeader:"⚠ Gender",                icon:"⚠",  iconType:"MANDATORY",    displayLabel:"Gender",               renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"options:Men,Women,Kids,Unisex",  hint:null },
    { colIndex:11, key:"Fit Type",             rawHeader:"Fit Type",                 icon:"",   iconType:"TEXT",         displayLabel:"Fit Type",             renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"options:Regular,Slim,Relaxed,Oversized,Athletic", hint:null },
    { colIndex:12, key:"Neckline",             rawHeader:"Neckline",                 icon:"",   iconType:"TEXT",         displayLabel:"Neckline",             renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"options:Round Neck,V-Neck,Collar,Hooded,Mock Neck", hint:null },
    { colIndex:13, key:"Sleeve Type",          rawHeader:"Sleeve Type",              icon:"",   iconType:"TEXT",         displayLabel:"Sleeve Type",          renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"options:Half,Full,Sleeveless,3-4,Raglan", hint:null },
    { colIndex:14, key:"MAIN FABRIC USED",     rawHeader:"→ MAIN FABRIC USED",      icon:"→",  iconType:"FK",           displayLabel:"Main Fabric",          renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:"RM Code", fkSheet:"RM_MASTER_FABRIC", validation:null, hint:"Search by RM code or fabric name" },
    { colIndex:15, key:"Fabric Name",          rawHeader:"← Fabric Name (Auto)",    icon:"←",  iconType:"AUTO_DISPLAY", displayLabel:"Fabric Name",          renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:"RM_MASTER_FABRIC",   validation:null,                          hint:null },
    { colIndex:16, key:"Color Codes",          rawHeader:"⟷ Color Code(s)",         icon:"⟷",  iconType:"SYNC",         displayLabel:"Color Code(s)",        renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:"COLOR_MASTER",       validation:null,                          hint:"Multi-select from COLOR_MASTER" },
    { colIndex:17, key:"Size Range",           rawHeader:"Size Range",               icon:"",   iconType:"TEXT",         displayLabel:"Size Range",           renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null,                          hint:"Display only e.g. XS-3XL" },
    { colIndex:18, key:"FINAL MARKUP %",       rawHeader:"∑ FINAL MARKUP %",        icon:"∑",  iconType:"CALCULATED",   displayLabel:"Final Markup %",       renderType:"percentage",mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null,                  validation:null,                          hint:"(MRP−WSP)÷WSP×100" },
    { colIndex:19, key:"FINAL MARKDOWN %",     rawHeader:"∑ FINAL MARKDOWN %",      icon:"∑",  iconType:"CALCULATED",   displayLabel:"Final Markdown %",     renderType:"percentage",mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null,                  validation:null,                          hint:"(MRP−WSP)÷MRP×100" },
    { colIndex:20, key:"WSP (Rs)",             rawHeader:"⚠ W.S.P (Rs)",            icon:"⚠",  iconType:"MANDATORY",    displayLabel:"W.S.P (₹)",            renderType:"currency",  mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null,                          hint:"Wholesale price per piece" },
    { colIndex:21, key:"MRP (Rs)",             rawHeader:"⚠ MRP (Rs)",              icon:"⚠",  iconType:"MANDATORY",    displayLabel:"MRP (₹)",              renderType:"currency",  mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null,                          hint:"Maximum retail price" },
    { colIndex:22, key:"HSN Code",             rawHeader:"→ HSN Code",              icon:"→",  iconType:"FK",           displayLabel:"HSN Code",             renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:"HSN Code", fkSheet:"HSN_MASTER",    validation:null,                          hint:null },
    { colIndex:23, key:"GST %",                rawHeader:"← GST % (Auto)",          icon:"←",  iconType:"AUTO_DISPLAY", displayLabel:"GST %",                renderType:"percentage",mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:"HSN_MASTER",         validation:null,                          hint:null },
    { colIndex:24, key:"Status",               rawHeader:"Status",                   icon:"",   iconType:"TEXT",         displayLabel:"Status",               renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"options:Active,Inactive,Development,Discontinued", hint:null },
    { colIndex:25, key:"Remarks",              rawHeader:"Remarks",                  icon:"",   iconType:"TEXT",         displayLabel:"Remarks",              renderType:"textarea",  mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null,                          hint:null },
    { colIndex:26, key:"Tags",                 rawHeader:"⟷ Tags",                  icon:"⟷",  iconType:"SYNC",         displayLabel:"Tags",                 renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:"TAG_MASTER",          validation:null,                          hint:"Multi-select tags" },
  ]
};

// ─── RM_MASTER_FABRIC (key cols) ──────────────────────────────────────────────
const RM_MASTER_FABRIC = {
  sheetName:   "RM_MASTER_FABRIC",
  fileLabel:   "FILE-1A",
  tabColor:    "#6aa84f",
  totalColumns: 25,
  dataStartRow: 4,
  fields: [
    { colIndex:1,  key:"RM Code",              rawHeader:"# RM Code",               icon:"#",  iconType:"AUTO_CODE",    displayLabel:"RM Code",              renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null,                  validation:null, hint:"Auto: RM-FAB-001" },
    { colIndex:2,  key:"FINAL FABRIC SKU",     rawHeader:"∑ FINAL FABRIC SKU",      icon:"∑",  iconType:"CALCULATED",   displayLabel:"Final Fabric SKU",     renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null,                  validation:null, hint:"GAS builds: KNIT NAME + YARN COMPOSITION" },
    { colIndex:3,  key:"KNIT NAME",            rawHeader:"→ KNIT NAME",             icon:"→",  iconType:"FK",           displayLabel:"Knit Structure",       renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:"Type Code", fkSheet:"FABRIC_TYPE_MASTER", validation:null, hint:"SJ/PIQ/FLC etc." },
    { colIndex:4,  key:"YARN COMPOSITION",     rawHeader:"⟷ YARN COMPOSITION",      icon:"⟷",  iconType:"SYNC",         displayLabel:"Yarn Composition",     renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:"RM_MASTER_YARN",      validation:null, hint:"Multi-select FK → RM_MASTER_YARN. Two-way sync." },
    { colIndex:5,  key:"Yarn Names",           rawHeader:"← Yarn Names (Auto)",     icon:"←",  iconType:"AUTO_DISPLAY", displayLabel:"Yarn Names",           renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:"RM_MASTER_YARN",      validation:null, hint:null },
    { colIndex:6,  key:"FABRIC TYPE",          rawHeader:"⚠ FABRIC TYPE",           icon:"⚠",  iconType:"MANDATORY",    displayLabel:"Fabric Type",          renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"options:KORA,FINISHED", hint:"KORA = greige. FINISHED = processed." },
    { colIndex:7,  key:"COLOUR",               rawHeader:"⚠ COLOUR",                icon:"⚠",  iconType:"MANDATORY",    displayLabel:"Colour Type",          renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"options:KORA,COLOURED,DYED,MELANGE", hint:null },
    { colIndex:8,  key:"GSM",                  rawHeader:"⚠ GSM",                   icon:"⚠",  iconType:"MANDATORY",    displayLabel:"GSM",                  renderType:"number",    mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null, hint:"Grams per square metre" },
    { colIndex:9,  key:"Width (inches)",       rawHeader:"Width (inches)",           icon:"",   iconType:"TEXT",         displayLabel:"Width (inches)",       renderType:"number",    mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null, hint:null },
    { colIndex:10, key:"UOM",                  rawHeader:"→ UOM",                   icon:"→",  iconType:"FK",           displayLabel:"UOM",                  renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:"UOM Code", fkSheet:"UOM_MASTER",    validation:null, hint:"KG / MTR / ROLL" },
    { colIndex:11, key:"HSN Code",             rawHeader:"→ HSN Code",              icon:"→",  iconType:"FK",           displayLabel:"HSN Code",             renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:"HSN Code", fkSheet:"HSN_MASTER",    validation:null, hint:null },
    { colIndex:12, key:"GST %",                rawHeader:"← GST % (Auto)",          icon:"←",  iconType:"AUTO_DISPLAY", displayLabel:"GST %",                renderType:"percentage",mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:"HSN_MASTER",         validation:null, hint:null },
    { colIndex:13, key:"Primary Supplier",     rawHeader:"→ Primary Supplier",      icon:"→",  iconType:"FK",           displayLabel:"Primary Supplier",     renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:"SUP Code", fkSheet:"SUPPLIER_MASTER", validation:null, hint:null },
    { colIndex:14, key:"Supplier Name",        rawHeader:"← Supplier Name (Auto)",  icon:"←",  iconType:"AUTO_DISPLAY", displayLabel:"Supplier Name",        renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:"SUPPLIER_MASTER",    validation:null, hint:null },
    { colIndex:25, key:"Tags",                 rawHeader:"⟷ Tags",                  icon:"⟷",  iconType:"SYNC",         displayLabel:"Tags",                 renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:"TAG_MASTER",          validation:null, hint:null },
  ]
};

// ─── TRIM_MASTER (key cols) ───────────────────────────────────────────────────
const TRIM_MASTER = {
  sheetName:   "TRIM_MASTER",
  fileLabel:   "FILE-1A",
  tabColor:    "#e69138",
  totalColumns: 29,
  dataStartRow: 4,
  fields: [
    { colIndex:1,  key:"Trim Code",            rawHeader:"# Trim Code",             icon:"#",  iconType:"AUTO_CODE",    displayLabel:"Trim Code",            renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null,             validation:null, hint:"Auto: TRM-THD-001" },
    { colIndex:2,  key:"Trim Name",            rawHeader:"⚠ Trim Name",             icon:"⚠",  iconType:"MANDATORY",    displayLabel:"Trim Name",            renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,             validation:null, hint:null },
    { colIndex:3,  key:"Trim Category",        rawHeader:"⚠ Trim Category",         icon:"⚠",  iconType:"MANDATORY",    displayLabel:"Trim Category",        renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,             validation:"options:THD,LBL,ELS,ZIP,BUT,TPE,DRW,VLC,RVT,THP,OTH", hint:null },
    { colIndex:4,  key:"Trim Sub-Category",    rawHeader:"Trim Sub-Category",        icon:"",   iconType:"TEXT",         displayLabel:"Sub-Category",         renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,             validation:null, hint:"e.g. Sewing Thread / CROCHET Elastic / BADGE" },
    { colIndex:5,  key:"IMAGE LINK",           rawHeader:"IMAGE LINK",               icon:"",   iconType:"TEXT",         displayLabel:"Trim Image",           renderType:"image_url", mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,             validation:null, hint:"1 image per SKU" },
    { colIndex:6,  key:"COLOUR CODE",          rawHeader:"→ COLOUR CODE",           icon:"→",  iconType:"FK",           displayLabel:"Colour Code",          renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:"Color Code", fkSheet:"COLOR_MASTER", validation:null, hint:null },
    { colIndex:7,  key:"Color Name",           rawHeader:"← Color/Shade Name (Auto)",icon:"←", iconType:"AUTO_DISPLAY", displayLabel:"Color / Shade Name",   renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:"COLOR_MASTER",   validation:null, hint:null },
    { colIndex:8,  key:"UOM",                  rawHeader:"UOM",                      icon:"",   iconType:"TEXT",         displayLabel:"UOM",                  renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,             validation:"options:CONE,MTR,PCS,KG,SET,ROLL", hint:null },
    { colIndex:9,  key:"HSN Code",             rawHeader:"→ HSN Code",              icon:"→",  iconType:"FK",           displayLabel:"HSN Code",             renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:"HSN Code", fkSheet:"HSN_MASTER", validation:null, hint:null },
    { colIndex:10, key:"GST %",                rawHeader:"← GST % (Auto)",          icon:"←",  iconType:"AUTO_DISPLAY", displayLabel:"GST %",                renderType:"percentage",mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:"HSN_MASTER",     validation:null, hint:null },
  ]
};

// ─── PO_MASTER (key cols, FILE 2) ─────────────────────────────────────────────
const PO_MASTER = {
  sheetName:   "PO_MASTER",
  fileLabel:   "FILE-2",
  tabColor:    "#cc0000",
  totalColumns: 18,
  dataStartRow: 4,
  fields: [
    { colIndex:1,  key:"PO Number",            rawHeader:"# PO Number",             icon:"#",  iconType:"AUTO_CODE",    displayLabel:"PO Number",            renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null,                  validation:null, hint:"Auto: PO-2026-001" },
    { colIndex:2,  key:"PO Date",              rawHeader:"⚠ PO Date",               icon:"⚠",  iconType:"MANDATORY",    displayLabel:"PO Date",              renderType:"date",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null, hint:null },
    { colIndex:3,  key:"Supplier Code",        rawHeader:"→ Supplier Code",         icon:"→",  iconType:"FK",           displayLabel:"Supplier",             renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:"SUP Code", fkSheet:"SUPPLIER_MASTER", validation:null, hint:null },
    { colIndex:4,  key:"Supplier Name",        rawHeader:"← Supplier Name (Auto)",  icon:"←",  iconType:"AUTO_DISPLAY", displayLabel:"Supplier Name",        renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:"SUPPLIER_MASTER",    validation:null, hint:null },
    { colIndex:5,  key:"PO Type",              rawHeader:"⚠ PO Type",               icon:"⚠",  iconType:"MANDATORY",    displayLabel:"PO Type",              renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"options:Fabric,Yarn,Trim,Consumable,Packaging,Mixed", hint:null },
    { colIndex:6,  key:"Season",               rawHeader:"Season",                   icon:"",   iconType:"TEXT",         displayLabel:"Season",               renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"options:SS25,AW25,SS26,AW26,Year Round", hint:null },
    { colIndex:7,  key:"Expected Delivery",    rawHeader:"Expected Delivery",        icon:"",   iconType:"TEXT",         displayLabel:"Expected Delivery",    renderType:"date",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null, hint:null },
    { colIndex:8,  key:"Base Amount",          rawHeader:"∑ Base Amount",           icon:"∑",  iconType:"CALCULATED",   displayLabel:"Base Amount (₹)",      renderType:"currency",  mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null,                  validation:null, hint:"Auto-sum from line items" },
    { colIndex:9,  key:"GST Amount",           rawHeader:"∑ GST Amount",            icon:"∑",  iconType:"CALCULATED",   displayLabel:"GST Amount (₹)",       renderType:"currency",  mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null,                  validation:null, hint:"Auto-sum from line items" },
    { colIndex:10, key:"Grand Total",          rawHeader:"∑ Grand Total",           icon:"∑",  iconType:"CALCULATED",   displayLabel:"Grand Total (₹)",      renderType:"currency",  mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null,                  validation:null, hint:"Base + GST" },
    { colIndex:11, key:"Status",               rawHeader:"Status",                   icon:"",   iconType:"TEXT",         displayLabel:"Status",               renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:"options:Draft,Approved,Sent,Partially Received,Fully Received,Cancelled", hint:null },
    { colIndex:12, key:"Remarks",              rawHeader:"Remarks",                  icon:"",   iconType:"TEXT",         displayLabel:"Remarks",              renderType:"textarea",  mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null,                  validation:null, hint:null },
  ]
};

// ─── SUPPLIER_MASTER (FILE 1C, key cols) ─────────────────────────────────────
const SUPPLIER_MASTER = {
  sheetName:   "SUPPLIER_MASTER",
  fileLabel:   "FILE-1C",
  tabColor:    "#674ea7",
  totalColumns: 20,
  dataStartRow: 4,
  fields: [
    { colIndex:1,  key:"SUP Code",             rawHeader:"# SUP Code",              icon:"#",  iconType:"AUTO_CODE",    displayLabel:"Supplier Code",        renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null, validation:null, hint:"Auto: SUP-001" },
    { colIndex:2,  key:"Supplier Name",        rawHeader:"⚠ Supplier Name",         icon:"⚠",  iconType:"MANDATORY",    displayLabel:"Supplier Name",        renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:null, hint:"Full legal name" },
    { colIndex:3,  key:"GSTIN",                rawHeader:"GSTIN",                    icon:"",   iconType:"TEXT",         displayLabel:"GSTIN",                renderType:"gstin",     mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:"regex:^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$", hint:"15-character GSTIN" },
    { colIndex:4,  key:"Contact Phone",        rawHeader:"Contact Phone",            icon:"",   iconType:"TEXT",         displayLabel:"Contact Phone",        renderType:"phone",     mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:"regex:^[0-9]{10}$", hint:null },
    { colIndex:5,  key:"Contact Email",        rawHeader:"Contact Email",            icon:"",   iconType:"TEXT",         displayLabel:"Contact Email",        renderType:"email",     mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:"email", hint:null },
    { colIndex:6,  key:"Category",             rawHeader:"⚠ Category",              icon:"⚠",  iconType:"MANDATORY",    displayLabel:"Category",             renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:"options:Fabric,Yarn,Trim,Consumable,Packaging,Multi-category", hint:null },
    { colIndex:7,  key:"City",                 rawHeader:"City",                     icon:"",   iconType:"TEXT",         displayLabel:"City",                 renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:null, hint:null },
    { colIndex:8,  key:"State",                rawHeader:"State",                    icon:"",   iconType:"TEXT",         displayLabel:"State",                renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:null, hint:null },
    { colIndex:9,  key:"Status",               rawHeader:"Status",                   icon:"",   iconType:"TEXT",         displayLabel:"Status",               renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:"options:Active,Inactive,Blacklisted", hint:null },
    { colIndex:10, key:"Remarks",              rawHeader:"Remarks",                  icon:"",   iconType:"TEXT",         displayLabel:"Remarks",              renderType:"textarea",  mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:null, hint:null },
  ]
};

// ─── COLOR_MASTER ─────────────────────────────────────────────────────────────
const COLOR_MASTER = {
  sheetName:   "COLOR_MASTER",
  fileLabel:   "FILE-1A",
  tabColor:    "#e06666",
  totalColumns: 8,
  dataStartRow: 4,
  fields: [
    { colIndex:1, key:"Color Code",           rawHeader:"# Color Code",            icon:"#",  iconType:"AUTO_CODE",    displayLabel:"Color Code",           renderType:"text",      mandatory:false, editable:false, autoGenerated:true,  fk:null, fkSheet:null, validation:null, hint:"Auto: COL-001" },
    { colIndex:2, key:"Color Name",           rawHeader:"⚠ Color Name",            icon:"⚠",  iconType:"MANDATORY",    displayLabel:"Color Name",           renderType:"text",      mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:null, hint:"e.g. Navy Blue, Off White" },
    { colIndex:3, key:"Hex Code",             rawHeader:"⚠ Hex Code",              icon:"⚠",  iconType:"MANDATORY",    displayLabel:"Hex Code",             renderType:"color_hex", mandatory:true,  editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:"regex:^#[0-9A-Fa-f]{6}$", hint:"#RRGGBB format" },
    { colIndex:4, key:"Color Family",         rawHeader:"Color Family",             icon:"",   iconType:"TEXT",         displayLabel:"Color Family",         renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:"options:Red,Blue,Green,Yellow,White,Black,Grey,Brown,Multi", hint:null },
    { colIndex:5, key:"Pantone Code",         rawHeader:"Pantone Code",             icon:"",   iconType:"TEXT",         displayLabel:"Pantone Code",         renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:null, hint:"Optional Pantone reference" },
    { colIndex:6, key:"Status",               rawHeader:"Status",                   icon:"",   iconType:"TEXT",         displayLabel:"Status",               renderType:"text",      mandatory:false, editable:true,  autoGenerated:false, fk:null, fkSheet:null, validation:"options:Active,Inactive", hint:null },
  ]
};

// ─── EXPORT — all mock schemas ────────────────────────────────────────────────

export const MOCK_SCHEMAS = {
  ARTICLE_MASTER,
  RM_MASTER_FABRIC,
  TRIM_MASTER,
  PO_MASTER,
  SUPPLIER_MASTER,
  COLOR_MASTER,
};

// Helper: get mock FK options for a sheet
export const MOCK_FK_OPTIONS = {
  RM_MASTER_FABRIC: [
    { code: "RM-FAB-001", name: "Single Jersey 180 GSM" },
    { code: "RM-FAB-002", name: "Pique 220 GSM" },
    { code: "RM-FAB-003", name: "Fleece 280 GSM" },
    { code: "RM-FAB-004", name: "Interlock 200 GSM" },
  ],
  HSN_MASTER: [
    { code: "6109", name: "T-Shirts, Singlets — 12% GST" },
    { code: "6105", name: "Shirts (Knitted) — 12% GST" },
    { code: "6110", name: "Jerseys, Pullovers — 12% GST" },
    { code: "5205", name: "Cotton Yarn — 5% GST" },
    { code: "6001", name: "Pile Fabrics — 5% GST" },
  ],
  COLOR_MASTER: [
    { code: "COL-001", name: "Navy Blue" },
    { code: "COL-002", name: "Off White" },
    { code: "COL-003", name: "Black" },
    { code: "COL-004", name: "Charcoal Melange" },
  ],
  SUPPLIER_MASTER: [
    { code: "SUP-001", name: "Vardhman Textiles Ltd" },
    { code: "SUP-002", name: "Nahar Industrial Enterprises" },
    { code: "SUP-003", name: "Trident Group" },
  ],
  TAG_MASTER: [
    { code: "TAG-001", name: "Bestseller" },
    { code: "TAG-002", name: "Export Quality" },
    { code: "TAG-003", name: "New Launch" },
    { code: "TAG-004", name: "Seasonal" },
  ],
  ITEM_CATEGORIES: [
    { code: "CAT-001", name: "Tops — Polo" },
    { code: "CAT-002", name: "Tops — Tee" },
    { code: "CAT-003", name: "Sweatshirt" },
    { code: "CAT-004", name: "Tracksuit" },
    { code: "CAT-005", name: "Bottoms" },
  ],
  UOM_MASTER: [
    { code: "KG",   name: "Kilogram" },
    { code: "MTR",  name: "Metre" },
    { code: "PCS",  name: "Pieces" },
    { code: "ROLL", name: "Roll" },
    { code: "CONE", name: "Cone" },
  ],
  FABRIC_TYPE_MASTER: [
    { code: "SJ",  name: "Single Jersey" },
    { code: "PIQ", name: "Pique" },
    { code: "FLC", name: "Fleece" },
    { code: "INT", name: "Interlock" },
    { code: "RIB", name: "Rib" },
  ],
};

export default MOCK_SCHEMAS;
